"""user_id_int_images

Revision ID: 49ff7050a326
Revises: 552281ed8f49
Create Date: 2024-12-03 17:17:06.084795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49ff7050a326'
down_revision: Union[str, None] = '552281ed8f49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'image', 'userprofile', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'image', type_='foreignkey')
    op.drop_column('image', 'user_id')
    # ### end Alembic commands ###
